# Generated by Django 3.2.2 on 2023-10-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('closedverse_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='user_ptr',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text="Allow this user to access the admin panel you're using right now? Don't forget to specify the permissions."),
        ),
        migrations.DeleteModel(
            name='ConversationInvite',
        ),
        migrations.DeleteModel(
            name='UserRequest',
        ),
    ]
