# Generated by Django 3.2.2 on 2023-10-16 21:10

import closedverse_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0002_auto_20231016_1355'),
    ]

    operations = [
		migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='comment_file/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='message_file/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='post_file/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_input',
            field=models.CharField(blank=True, help_text='Input a Mii Hash, or URL depending on what "Avatar type" is set to..', max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_type',
            field=models.SmallIntegerField(choices=[(0, 'ImageField'), (1, 'URL / Gravatar'), (2, 'Mii Hash'), (3, 'Mii Studio')], default=False, help_text='Determines the type of avatar this user has.'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_upload',
            field=models.ImageField(blank=True, help_text='Note this only works if you have "Avatar type" set to "ImageField"', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_announcements',
            field=models.BooleanField(default=True),
        ),
    ]
