# Generated by Django 3.2.2 on 2023-10-16 22:02

import closedverse_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0004_auto_20231016_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='drawing',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='message',
            name='drawing',
        ),
        migrations.RemoveField(
            model_name='message',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='post',
            name='drawing',
        ),
        migrations.RemoveField(
            model_name='post',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bg_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_mh',
        ),
        migrations.AlterField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='community_banners/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='ico',
            field=models.ImageField(blank=True, null=True, upload_to='community_icons/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='url',
            field=models.URLField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='external',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronoun_is',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weblink',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatareyou',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='color',
            field=closedverse_main.models.ColorField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
