# Generated by Django 3.2.3 on 2022-09-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersban',
            name='reason',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
