# Generated by Django 3.2.3 on 2022-09-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ban', '0002_usersban_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersban',
            name='reason',
        ),
    ]
